### PR TITLE
Remove Lachlan from VIP newsletter headers

### PR DESCRIPTION
**Pull request by cjdenio**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/vip-newsletters/\[slug\]**](https://workshops-g9sebilyr.hackclub.dev/vip-newsletters/[slug]) |
|:-:|
|<a href="https://workshops-g9sebilyr.hackclub.dev/vip-newsletters/[slug]">Screenshot of /vip-newsletters/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/pUXDKZpd8deCOJ8f374LvYwkCG5zbim4yFiOrIARcCnNuC1hkeukPjb2DmGwcX7Ak2MrDFFV4a2vGd-yEUcXhw.png">(view full size)</a> |







Commit 05745115d1eba5f7d89be5939c07053c99184841 (https://workshops-g9sebilyr.hackclub.dev).

**Review by sampoder — APPROVED** [review]
👍

**Comment by cjdenio** [comment]
👀

**Comment by zachlatta** [comment]
Makes sense. Thank you for all the amazing work you did helping start the newsletter @lachlanjc!

**Pull request merged**
