### PR TITLE
For Deploy on Monday: Sunset SoM Letter Draft

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/sunsetting-som**](https://workshops-git-fork-sampoder-main.hackclub.dev/sunsetting-som) |
|:-:|
|<a href="https://workshops-git-fork-sampoder-main.hackclub.dev/sunsetting-som">Screenshot of /sunsetting-som</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_4_2HUSoFozNBeCeL7vHulOpx2c_.png">(view full size)</a> |







Commit 1a25b01d0af597526b6cf1a1e902083f33b2f4e0 (https://workshops-git-fork-sampoder-main.hackclub.dev).

**Comment by sampoder** [comment]
fyi the page's title is COVID-19 coz of #21

**Comment by lachlanjc** [comment]
Amazing work here, thanks for stepping up. I'll do a pass of edits but great work.

**Comment by lachlanjc** [comment]
I’ve fleshed out & made some corrections/edits to the letter, but thank you for writing this!! Feel free to change things if you don’t like my wording, this is coming from you so I want you to have full confidence & ownership of it.

**Pull request merged**
